[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
;
; Adjust the upload_port if necessary for your system.
;
; Required libraries:
lib_deps =
  adafruit/Adafruit SSD1306@^2.5.7
  adafruit/Adafruit GFX Library@^1.11.8
  adafruit/Adafruit INA219@^1.0.5
  adafruit/DHT sensor library@^1.4.3

build_flags =
  -DARDUINO_ARCH_ESP32

src_dir = src
